pimcore:
  documents:
    editables:
      map:
        editortype: \Pimcorecasts\Bundle\EditorTypeBundle\Model\Document\Editable\EditorType

  objects:
    class_definitions:
      data:
        map:
          editorType: \Pimcorecasts\Bundle\EditorTypeBundle\Model\DataObject\ClassDefinition\Data\EditorType